### PR TITLE
BONGBONGBONGBONGBONGBONGBONGBONGBONGBONGBONGBONGBONG BANANANANA

### PR DESCRIPTION
**Pull request by SwadicalRag**
sorry i'm going insane with these pull requests

### CODE REVIEW

**Comment by bmwalters** [comment]
why are you doing this via the web interface? `git fetch origin; git merge origin/simplify`

**Comment by SwadicalRag** [comment]
cause idk how to git

**Comment by SwadicalRag** [comment]
i use sourcetree and it's ass sometimes

**Comment by MDFL64** [comment]
gitkraken is good as heck

**Pull request merged**
